[package]
name = "usmc"
version = "0.1.0"
edition = "2021"

[lib]
name = "usmc"
path = "src/lib.rs"

[[bin]]
name = "usmc"
path = "src/main.rs"

[dependencies]
eframe = "0.27"
egui = "0.27"
rand = "0.8"
libloading = "0.8"

[[test]]
name = "usmc_tests"
path = "tests/usmc_tests.rs"